### ISSUE TITLE
can't use inside ng-grid/ui-grid

### ISSUE THREAD

**Issue by madhav5589** [minhur/bootstrap-toggle#10]
I am trying to use bootstraptoggle withing ng-grid (newer version is called ui-grid)- http://angular-ui.github.io/ng-grid/ . 
I can not see toggle button. I can see checkbox instead of toggle. Not sure is it still in developement or what.  
![snap](https://cloud.githubusercontent.com/assets/7840180/5040233/7270a958-6b60-11e4-8363-55eb4347571c.PNG)

**Comment by minhur** [comment]
you need to make sure the checkbox has `data-toggle="toggle"`
here's a demo of this working with ng-grid
http://plnkr.co/edit/qkx9NsQcmKaxtCbQO1TO?p=preview
