### ISSUE TITLE
event listening: is only 'change' propagated? or How to set state with script without activating 'change'

### ISSUE THREAD

**Issue by jhub95** [minhur/bootstrap-toggle#103]
No problem using `$("#inputID").on('change')` but for the life of me I can't attach a click listener to the toggle.  I've tried `onClick="console.log(this)"` directly on the input and also `$("#inputID").on('click')` but neither seem to work.  
The root of the question is in that I need two listeners. Why? Because my initial script sets the toggle state according to an object property. Whenever this script sets the toggle state using `$('#inputID').bootstrapToggle('on')` it activates the `$("#inputID").on('change')` listener. Then when a user actually clicks on the toggle` $("#inputID").on('change')` is again activated.  I don't want the 'change' to happen twice, once with the initial script and secondly with the click. I want it just once on user click.  So I was thinking I could use the 'click' listener, but it doesn't seem to be propagating from the generated divs/label/span.

**Comment by zorba128** [comment]
Few days ago I had exactly same problem - finally implemented not-so-nice workaround which works by switching state of underlying control without change event raised, and then manually forcing toggle update - also without notifications.

```
var toggle = $("#inputID").data('bs.toggle');
$("#inputID").prop("checked", isChecked)
if(toggle) toggle.update(true)
```

**Comment by ccaper** [comment]
I too am in a scenario where I need to differentiate between a click and a change.

**Comment by jhub95** [comment]
In the end this issue has made me abandon bootstrap-toggle.  In its place I'm using bootstrap-switch http://www.bootstrap-switch.org which has a way to activate the toggle without activating the 'change' event.

**Comment by dustinb** [comment]
I used http://kleinejan.github.io/titatoggle/, works great

**Comment by mariusa** [comment]
Indeed, change fires twice, similar to this issue
https://github.com/Bttstrp/bootstrap-switch/issues/175

Need  a custom even for change, please
