### ISSUE TITLE
API does not work in my web page

### ISSUE THREAD

**Issue by paul-cheung** [minhur/bootstrap-toggle#104]
what i am referring is like below:
`<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>`
`<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">`
`<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>`

when i use `$('#toggle-one').bootstrapToggle();`, the error says "Uncaught TypeError: $(...).bootstrapToggle is not a function", what i missed?

**Comment by Lydecker** [comment]
remove the function around it so it is just 

```
<script>
$('#toggle-one').bootstrapToggle();
</script>

```

**Comment by raluca-san** [comment]
I get the same error. has someone find a solution already?

**Comment by asahajit** [comment]
API is not working  is there any solution for "$(...).bootstrapToggle is not a function"
