### ISSUE TITLE
Toggle is not binded to checkbox value nor checked property

### ISSUE THREAD

**Issue by milmih** [minhur/bootstrap-toggle#140]
### Note

Possible duplicate of https://github.com/minhur/bootstrap-toggle/issues/111.

### Problem

If you open http://www.bootstraptoggle.com/, fire up devtools console and run (checkbox is on, toggle is on):

```
>  $('.example input:first').prop('checked')
<- true
>  $('.example input:first').prop('checked', false)
<- [input]
>  $('.example input:first').prop('checked')
<- false
```

or:

```
>  $('.example input:first').val()
<- "on"
>  $('.example input:first').val('off')
<- [input]
>  $('.example input:first').val()
<- "off"
```

toggle doesn't get updated.

Also, toggle first changes it state upon click and then _onChange_ event on checkbox input is invoked.

### Proposed solution

1. Bind the state of toggle to the state of checkbox.
2. Do not assume that state will be changed (since it can be prevented in _onChange_ event handler or in other ways). Update the toggle state upon checkbox state has been updated.

**Comment by stosh15x** [comment]
This is my solution
```
$("input:checkbox").on('change', function(){
  var isChecked = $(this).is(':checked')
  $(this).val(Number(isChecked)).attr('checked', isChecked)
});
```
