### ISSUE TITLE
Error: "Too much recursion"

### ISSUE THREAD

**Issue by caio000** [minhur/bootstrap-toggle#156]
I have a function to change the button status, but I has the error "too much recursion". The code is below.
```javascript
function setAllMarkers(showSec) {
        var param = (showSec) ? map : null;
        var option  = (showSec) ? "on" : "off";

        $('input[name=btnShowSec]').bootstrapToggle(option);

        for (var i = 0; i < markers.length; i++)
          markers[i].setMap(param);
      }
```

**Comment by sbsatter** [comment]
where is setAllMarkers called?

If it's related to the change event, then every time you toggle, the change event occurs again, which might execute setAllMarkers again. Hence, this goes in an infinite loop!

**Comment by kirin2** [comment]
Hi this is an issue on changing the state of the toogle. Changing the state of the toogle triggers change event so when inside such event error Too much recursion occurs

Before you change the toggle on or off check what the current state of the toogle

you should do something like. Adjust below code where suite your situation

```
function setAllMarkers(showSec) {
        var param = (showSec) ? map : null;
        var option  = (showSec) ? "on" : "off";
        
        if($('input[name=btnShowSec]:checked') == false && showSec == true){
			
			$('input[name=btnShowSec]').bootstrapToggle("on");
			
		}
		///else not need since default is off

        for (var i = 0; i < markers.length; i++)
          markers[i].setMap(param);
}
```

**Comment by caio000** [comment]
Thanks guys its work!
