### ISSUE TITLE
Reset not working

### ISSUE THREAD

**Issue by Cravid** [minhur/bootstrap-toggle#17]
The toggle checkboxes do not work with the standard html input type="reset".

**Comment by Cravid** [comment]
Just to mention I may not reopen this issue as I did not close it.

**Comment by minhur** [comment]
I don't plan on supporting this feature.

`<form>` tag's `reset` event triggers before the fields's `change` event, making it hard to listen in on the dom change event *after* the form has been reset. Refer to mdn documentation on reset event to learn more.

The only workaround I would suggest here would be create a custom reset button that does a form reset using js, and update the toggles after the form reset completes.

Here's an example: http://jsfiddle.net/minhur/p8qbuepj/

**Comment by martinwnet** [comment]
Thanks for the workaround - I'd second/vote for this nice to have feature though, as it would mimic standard checkbox functionality.

**Comment by morrica** [comment]
I think the biggest issue here is that the underlying checkbox element does reset while the toggle visual does not. Meaning if the form is then submitted it will submit data that is not indicated by the toggle position. It would be good to have the checkboxes either work completely or not at all or have a very clear notice about the issue on the project's home page with a suggested workaround.
