### ISSUE TITLE
Not working on dynamically added contents

### ISSUE THREAD

**Issue by amalts** [minhur/bootstrap-toggle#21]
Dynamically added contents are not getting initialised automatically

**Comment by minhur** [comment]
you need to initialize them your self using api after the dom has the checkbox.
```js
$(':checkbox').bootstrapToggle()
```

**Comment by govindaraje** [comment]
$(':checkbox').bootstrapToggle()

It's working fine while adding dynamic bootstrap switch, Thank you so much
