### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by cgountanis** [minhur/bootstrap-toggle#210]
I would love to use something like this but DEV seems to have stalled. Is this project going to be updated for BS4 without work-arounds in the near future?

**Comment by djibe** [comment]
Hello, this project is dead and you should stick to brand new built-in Bootstrap 4 Switches available at https://getbootstrap.com/docs/4.3/components/forms/#switches

Enjoy.
Or you may try my fork of Bootstrap Switch : https://github.com/djibe/bootstrap-switch

**Comment by cgountanis** [comment]
Thanks
