### ISSUE TITLE
No working on iPhone

### ISSUE THREAD

**Issue by mewsoft** [minhur/bootstrap-toggle#22]
According to this thread:

https://github.com/nostalgiaz/bootstrap-switch/issues/412#issuecomment-69426375

He says not working on iPhone (e.g. iOS Safari).

**Comment by mewsoft** [comment]
Just wondering if this plugin still active and in development.

**Comment by minhur** [comment]
I've tested this with Safari on iPhone 4-5 and it works for me.

**Comment by mewsoft** [comment]
@minhur glad to hear from you that it is working on iPhone because I already used your nice plugin in production applications.
