### ISSUE TITLE
onchange function Runs twice.

### ISSUE THREAD

**Issue by omidmousavi** [minhur/bootstrap-toggle#232]
When i changed value by js code, for example :  `$("#id").prop('checked', true).change();  `
The onchange function of `#id` Runs twice...
Is there a way to avoid this problem?

**Comment by palcarazm** [comment]
Hi,
If you are using bootstrap 4 or 5, the latest plug-in version is https://palcarazm.github.io/bootstrap5-toggle/

**Comment by omidmousavi** [comment]
Hi, Thank you🙏, It is resolved and your link was very helpful. Thank you again.
