### ISSUE TITLE
Set Custom Widths and Spacing?

### ISSUE THREAD

**Issue by kraymitchell** [minhur/bootstrap-toggle#25]
How do I set custom Widths on the toggle?

I have a couple with long titles and they are being cut off. I also noticed that I must put a space after (On state) and before (Off state) to ensure proper spacing.

Thanks

**Comment by minhur** [comment]
https://github.com/minhur/bootstrap-toggle/issues/14

**Comment by kraymitchell** [comment]
Thank Minhur, 
I would like all the toggles to be the same width, but theres a couple issues with this method.

1. You cannot use the same ID for multiple items. I have attempted to add a custom class to the lnput, as well as trying with .toggle-on/.toggle-off with no luck (Even using !important). I managed to get the inside portion to go to the width I wanted, but obviously that doesn't help much.

2. !important is kind of a hack. I would prefer to set a standard width somewhere if possible.

**Comment by kraymitchell** [comment]
While I still think you should never use **!important** (This means there is a conflict you're trying to override. It's better to fix and avoid conflicts rather than duct tape fix them), this is the easiest way I could find to do it without ID's (As I have 15 of them on a page).

div[data-toggle="toggle"] { width:100px !important;}

Please offer an update to allow for this without **!important** being used.

**Comment by minhur** [comment]
I agree with you, it's just I haven't been able to get back on this project in the recent month.
this will come in the upcoming release. until then I just wanted to offer a workaround
