### ISSUE TITLE
Doesn't work with bootstrap dropdowns

### ISSUE THREAD

**Issue by quillford** [minhur/bootstrap-toggle#41]
This is the [repository](https://github.com/quillford/printerview) that has the code where I am trying to add the toggle.

Note, as of the time of this writing, I did not commit any changes with the toggle as it did not work as expected.
![](https://cloud.githubusercontent.com/assets/8762862/6886557/373e8872-d5f6-11e4-8aa6-4644c1a1ae56.png)

**Comment by regepan** [comment]
bootstrap-toggle worked well in the Bootstrap navbar dropdown.

![dropdown](http://regepan.github.io/hexo-blog/css/images/dropdown.png)

**Comment by mhebrard** [comment]
I have same trouble, in my navbar, the checkbox is not styling as toggle button
can you please show the code of the previous screen ?
