### ISSUE TITLE
Any reason why bootstrapToggle wouldn't work with Ember.js?

### ISSUE THREAD

**Issue by Shak-eah** [minhur/bootstrap-toggle#49]
Hello - I've been trying to get this to work with our Ember App, and I've been able to integrate other bootstrap plugins as per the usual method: include the library after including bootstrap, initialise via jquery if needed, and they work. However, both bootstrap toggle and bootstrap switch don't ever show up; they don't seem to apply themselves to the classes I need them to. 

Are you aware of any issues with Ember.js? If not, then there must be something in our application that's preventing it.

**Comment by briansol** [comment]
Do you 'add' to the dom the switches with ember?  If so, you probably need to hook the init call to something that exists in dom-scope at source render time.

         $('.iPrintBeforeDomReady .mycheckboxclass input[type="checkbox"]').bootstrapToggle();

**Comment by Shak-eah** [comment]
Ah it seems that the way I was doing it, trying to initialise in the didInsertElement hook, for whatever reason, tried to initialise before the DOM element was actually inserted. 

For anyone else having this issue, this might help:

        $(window).bind('load', function(){
            $('#toggle-one').bootstrapToggle(); //will run after page has loaded.

        });

Instead of simply 
            $('#toggle-one').bootstrapToggle(); //will run after page has loaded.

My immediate issue was resolved with this, although I'm sure there is a better way.
