### ISSUE TITLE
No Styling when added dynamically or after page load

### ISSUE THREAD

**Issue by LourensNewsclip** [minhur/bootstrap-toggle#65]
I am adding toggles after page has load via a $.GetJson() call but NO STYLING is applied.

See attached screenshot.

Note: It works just fine for the toggles that is hard coded.

![toggleissue](https://cloud.githubusercontent.com/assets/13256450/8597462/c56d3512-2655-11e5-9f51-e14dac216987.jpg)

**Comment by paulomcnally** [comment]
You need create an javascript event listener to execute initialize plugin.

**Comment by LourensNewsclip** [comment]
Thank you ... got it working by using

$('#tog' + index).bootstrapToggle();

**Comment by paulomcnally** [comment]
@LourensNewsclip Close this :)
