### ISSUE TITLE
Onchange doesnt fire in bootstrap toggle button on partial page load (update panel reload)

### ISSUE THREAD

**Issue by roshantarudkar** [minhur/bootstrap-toggle#67]
i have togglebutton in gridview and that is in update panel.
when i refersh the page and if i do toggling in button onchange event is getting fired but if i click on some other button lets say submit button ,so gird reloads the data and update panel updates ..now if i change the toggle active to inactive vice versa it changes but onchange event doesnt fire..
is it because of i am reloading on grid and not whole page is getting postback? 
i am stuck with this..can anyone please help me on this..

in grid i have below control:
 <input  type="checkbox" name="toggle-indicator" data-toggle="toggle" data-on="Active" data-off="InActive" data-size="small">

javasctipt
  $(document).ready(function () {
            $('input[name="toggle-indicator"]').change(function () {
                //get id from the grid
alert("onchange call");  });

**Comment by regepan** [comment]
Can you provide demo or full code?

**Comment by roshantarudkar** [comment]
in Aspx file i have code below:
<asp:UpdatePanel ID="updpnl" runat="server" UpdateMode="Conditional">
            <ContentTemplate>
             <div class="col-lg-12 form-group">
                     <asp:GridView ID="gvAutoAssign" runat="server" SkinID="sknGrdView" BorderStyle="none" SelectedRowStyle-BorderStyle="None" RowStyle-BorderStyle="none" AlternatingRowStyle-BorderStyle="none" AutoGenerateColumns="false">
                        <Columns>
                            <asp:TemplateField HeaderText="<%$ Resources: Resource, itemstatus %>">
                                <ItemTemplate>
                                    <input id="toggle-event" type="checkbox" name="toggle-indicator" data-toggle="toggle" data-on="Active" data-off="InActive" data-size="small">
                                  </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </div>
                 </ContentTemplate>
        </asp:UpdatePanel>


in javacript:
$(document).ready(function(){
 $('input[name="toggle-indicator"]').change(function () {
alert('blach');
 })
});

i suspect since toggle indicator is in update panel so again we need to bind jquery bind change event of the control but i have some many controls..every time ajax update panel calls i dont need to call change event all time..whenever i change toggle that time only i want to call change event.

**Comment by vermaslal** [comment]
This is happening because late binding.

You can try this. Here togCheck class is an element (parent element) that is not reloading and .check is element that is late loading (Using Ajax).

  $('.togCheck').on('change', '.check', function () {
      if (confirm("Are you sure")) {
        console.log($(this).prop('checked'));
      }
    });
